[package]
name = "hello_rustaceans"
version = "0.1.0"
edition = "2024"
default-run = "hello_rustaceans"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.13"
serde = { version = "1.0.219", features = ["derive"] }
